name: Build site and publish
on: push
jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: "cache"
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Standard usage
      - uses: helaili/jekyll-action@v2
        id: "build"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: "./"
          target_branch: "build"
          pre_build_commands: 'bundle update ffi; git config --global http.version HTTP/1.1'

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Call Hook PROD success
        uses: distributhor/workflow-webhook@v1
        if: ${{ always() }}
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_PROD }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: ${{ toJson(steps) }}

      - name: Call Hook STAGING success
        uses: distributhor/workflow-webhook@v1
        continue-on-error: true
        if: ${{ always() }}
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_STAGING }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: ${{ toJson(steps) }}

      - name: Call Hook LOCAL success
        uses: distributhor/workflow-webhook@v1
        continue-on-error: true
        if: ${{ always() }}
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_LOCAL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: ${{ toJson(steps) }}
